files:
  - source: app/src/main/res/values/strings.xml
    translation: app/src/main/res/values-%locale%/%original_file_name%
  skip_untranslated_strings: true
  export_pattern: app/src/main/res/values-%locale%/%original_file_name%
