blank_issues_enabled: false
contact_links:
  - name: 🧑‍💻 ReDantotsu Help on Discord
    url: https://discord.gg/GGdQumttZ
    about: Get support, ask questions, and join the community discussions.

  - name: 📱 ReDantotsu Help on Telegram
    url: https://t.me/redantotsuu
    about: Connect with the community, ask questions, and get help directly on Telegram.

